############
# Provide relevent paths
############

# Specify output directory
outdir: NA

# Location of this config file
config_file: NA

# Specify location of gwas_list file
gwas_list: NA

# Specify location of rosmap and banner data for PWAS and SMR
# These files can be downloaded from here: https://www.synapse.org/#!Synapse:syn23627957
rosmap_fusion: NA
banner_fusion: NA
rosmap_smr: NA

############
# Specify desired output
############

# Identify independent significant SNPs using clumping
clump: F

# Perform COJO analysis
cojo: F

# Perform SNP finemapping analysis
finemap: F

# Estimate SNP-heritability and intercept using LD score regression
ldsc: F

# MAGMA gene associations analysis
magma_gene: F

# MAGMA gene set enrichment analysis using DrugTargetor sets
magma_drugtargetor: F

# TWAS using FUSION and PsychENCODE panel
twas_panel_psychencode: F

# TWAS using FUSION panels
twas_panel_fusion: F

# Specify TWAS FUSION GTEx panels
gtex_weights: []

# Specify TWAS FUSION non-GTEx panels
non_gtex_weights: []

# Specify external TWAS panels in FUSION format
external_weights: F
external_weights_pos_path: []

# Conditional analyss of TWAS results
twas_conditional: F

# TWAS-GSEA gene property association analysis using DrugTargetor
twas_gsea_drugtargetor: F

# Run SMR using below panels
smr_expression_panel_psychencode: F
smr_expression_panel_metabrain_basalganglia: F
smr_expression_panel_metabrain_cerebellum: F
smr_expression_panel_metabrain_cortex: F
smr_expression_panel_metabrain_hippocampus: F
smr_expression_panel_metabrain_spinalcord: F
smr_expression_panel_eqtlgen: F

# Run PWAS using FUSION using below panels
pwas_panel_rosmap: F
pwas_panel_banner: F

# Run SMR using pQTL data from ROSMAP
smr_protein_panel_rosmap: F

# Run GCSC drug enrichment analysis
gcsc: F
gcsc_tissues: []

# MAGMA tissue enrichment
tissue_magma: F
