configfile: "config.yaml"

import os
import json
import gzip
import itertools
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

wildcard_constraints:
    version="[\d.]+",
    gwas="[^-]+",
    name="[^-]+",
    population="[^-]+",
    method="[^-]+"

include: "rules/dependencies.smk"
include: "rules/sumstat_qc.smk"
include: "rules/finemapping.smk"
include: "rules/magma.smk"
include: "rules/twas_pwas.smk"
include: "rules/smr.smk"
include: "rules/gcsc.smk"
include: "rules/report.smk"
