#!/usr/bin/env Rscript
#
# Generate the bundled gene-position reference (gene_positions.rds) used by the
# Molecular Associations per-locus layout to map every feature (gene symbol,
# alias, or Ensembl ID) to a single GRCh37 position.
#
# Source: the pipeline's authoritative biomart gene table, generated by
# pipeline/scripts/download_biomart.R and stored under {resdir}/data/biomart/.
# Columns: ensembl_gene_id, external_gene_name, external_synonym,
#          chromosome_name, start_position, end_position (GRCh37).
#
# Re-run this whenever the biomart reference is refreshed:
#   Rscript make_gene_positions.R [path/to/biomart_genes_grch37.tsv] [out.rds]
#
# Output: a list of three symbol-keyed data.frames (ID, CHR, BP), BP = gene
# midpoint, restricted to autosomes (chr 1-22):
#   by_symbol  external_gene_name -> CHR, BP
#   by_synonym external_synonym   -> CHR, BP
#   by_ensembl ensembl_gene_id    -> CHR, BP

suppressMessages(library(data.table))

args <- commandArgs(trailingOnly = TRUE)
in_tsv <- if (length(args) >= 1) args[1] else
  "/cephfs/volumes/hpc_data_prj/neurohackpain/47452046-c6ec-4387-999a-e1d08d957104/GenoDisc/pipeline_resources/data/biomart/biomart_genes_grch37.tsv"
out_rds <- if (length(args) >= 2) args[2] else "gene_positions.rds"

bm <- fread(in_tsv, na.strings = c("", "NA"))
bm <- bm[chromosome_name %in% as.character(1:22)]
bm[, CHR := as.integer(chromosome_name)]
bm[, BP := (as.numeric(start_position) + as.numeric(end_position)) / 2]
bm <- bm[!is.na(CHR) & !is.na(BP)]

make_map <- function(dt, key_col) {
  d <- dt[!is.na(get(key_col)) & get(key_col) != ""]
  d <- d[, .(ID = get(key_col), CHR, BP)]
  d <- d[!duplicated(ID)]              # first occurrence wins
  as.data.frame(d)
}

gene_positions <- list(
  by_symbol  = make_map(bm, "external_gene_name"),
  by_synonym = make_map(bm, "external_synonym"),
  by_ensembl = make_map(bm, "ensembl_gene_id")
)

saveRDS(gene_positions, out_rds, compress = "xz")

cat("Wrote", out_rds, "\n")
cat("  by_symbol :", nrow(gene_positions$by_symbol), "genes\n")
cat("  by_synonym:", nrow(gene_positions$by_synonym), "aliases\n")
cat("  by_ensembl:", nrow(gene_positions$by_ensembl), "ensembl ids\n")
