---
title: "Validation"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    toc_depth: 2

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
library(knitr)
```

***

# Initial test

```{r}

dir.create('/users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/', recursive = T)

library(data.table)

####
# Create gwas_list
####

gwas_list <- NULL

gwas_list_scz <- rbind(
  gwas_list,
  data.table(
    name = 'SCZ',
    path = '/users/k1806347/oliverpainfel/Data/GWAS_sumstats/GenoFuncPipe_paper/SCZ/SCZ.original.gz',
    population = 'EUR',
    n = NA,
    sampling = NA,
    prevalence = NA,
    mean = NA,
    sd = NA,
    label = 'SCZ'))

write.table(gwas_list_scz, '/users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/gwas_list_scz.txt', row.names = F)

gwas_list <- NULL

gwas_list_cad <- rbind(
  gwas_list,
  data.table(
    name = 'CAD',
    path = '/users/k1806347/oliverpainfel/Data/GWAS_sumstats/GenoFuncPipe_paper/CAD/GCST90132314.h.tsv.gz',
    population = 'EUR',
    n = NA,
    sampling = NA,
    prevalence = NA,
    mean = NA,
    sd = NA,
    label = 'CAD'))

write.table(gwas_list_cad, '/users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/gwas_list_cad.txt', row.names = F)

####
# Create config file
####

config_scz <- c(
  "outdir: /users/k1806347/oliverpainfel/Analyses/genodisc_validation/output", 
  "config_file: /users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/config_scz.yaml", 
  "gwas_list: /users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/gwas_list_scz.txt", 
  "ldsc: T", 
  "magma_gene: T", 
  "magma_drugtargetor: T",
  "twas_panel_psychencode: T",
  "twas_panel_fusion: T", 
  "gtex_weights: ['Whole_Blood']", 
  "non_gtex_weights: ['CMC.BRAIN.RNASEQ']", 
  "twas_gsea_drugtargetor: T",
  "twas_gsea_drugtargetor_nondirectional: T"
)

write.table(config_scz, '/users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/config_scz.yaml', col.names=F, row.names=F, quote=F)

config_cad <- c(
  "outdir: /users/k1806347/oliverpainfel/Analyses/genodisc_validation/output_cad", 
  "config_file: /users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/config_cad.yaml", 
  "gwas_list: /users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/gwas_list_cad.txt", 
  "ldsc: T", 
  "magma_gene: T", 
  "magma_drugtargetor: T",
  "twas_panel_fusion: T", 
  "gtex_weights: ['Whole_Blood']", 
  "twas_gsea_drugtargetor: T",
  "twas_gsea_cmap: T",
  "cmap_level5_prop: /users/k1806347/oliverpainfel/Data/CMAP/reprocessed/CMAP_level5/lvl5Allcompounds_population_TWAS-GSEA_prop.rds",
  "cmap_compoundinfo: /users/k1806347/oliverpainfel/Data/CMAP/compoundinfo_beta.txt",
  "twas_gsea_drugtargetor_nondirectional: T"
)

write.table(config_cad, '/users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/config_cad.yaml', col.names=F, row.names=F, quote=F)

```

```{bash}
cd /users/k1806347/oliverpainfel/Software/MyGit/GenoDisc/pipeline
conda activate genodisc
  
snakemake \
  --configfile=/users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/config_scz.yaml \
  --use-conda \
  --profile slurm \
  run_package_results \
  -n

snakemake \
  --configfile=/users/k1806347/oliverpainfel/Analyses/genodisc_validation/config/config_cad.yaml \
  --use-conda \
  --profile slurm \
  run_package_results \
  -n

```

```{r}
# Explore CMAP results for CAD
res<-fread('/users/k1806347/oliverpainfel/Analyses/genodisc_validation/output_cad/results/CAD/twas/cmap/twas_gsea_cmap_Whole_Blood.competitive.txt')

# Remove leading number from gene set name
res[, GeneSet := str_remove(GeneSet, '^\\d+\\.')]

library(tidyr)
library(dplyr)

res_clean <- res %>%
  separate(GeneSet, into = c("drug", "cell_type", "time", "dose"), sep = "_") %>%
  mutate(
    time_h = as.numeric(sub("h$", "", time)),
    dose_uM = as.numeric(sub("uM$", "", dose))
  ) %>%
  select(-time, -dose)


library(dplyr)
library(ggplot2)

drug_to_plot <- "BRD-K08799867"

plot_df <- res_clean %>%
  filter(drug == drug_to_plot) %>%
  mutate(
    condition = paste0(time_h, "h_", dose_uM, "uM"),
    neglog10_p = -log10(P),
    sig = P.CORR < 0.05
  )

ggplot(plot_df, aes(x = condition, y = cell_type)) +
  geom_point(aes(size = neglog10_p, colour = Estimate, shape = sig)) +
  scale_colour_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  labs(
    title = drug_to_plot,
    x = "Condition",
    y = "Cell type",
    colour = "Estimate",
    size = expression(-log[10](P)),
    shape = "P.CORR < 0.05"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

plot_df <- res_clean %>%
  filter(drug == drug_to_plot) %>%
  mutate(
    sig = P.CORR < 0.05,
    dose_uM = factor(dose_uM)
  )

ggplot(plot_df, aes(x = dose_uM, y = cell_type)) +
  geom_point(aes(size = abs(Estimate), colour = Estimate, shape = sig)) +
  facet_wrap(~ time_h, nrow = 1) +
  scale_colour_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  labs(
    title = paste("Associations for", drug_to_plot),
    x = "Dose (uM)",
    y = "Cell type",
    colour = "Estimate",
    size = "|Estimate|",
    shape = "P.CORR < 0.05"
  ) +
  theme_bw()
```

***

# Anqi

```{bash}
# Check sumstats provided by Anqi
ls ~/neurohackpain/anqi/DiseasesGwas/*
```

```{r}
dir.create('/scratch/prj/neurohackpain/anqi/genodisc_validation/config/', recursive = T)

library(data.table)

# Anqi has created the gwas_lists already

####
# Create config file
####

traits <- list.files('/scratch/prj/neurohackpain/anqi/DiseasesGwas/', full.names = F)

config_list <- list()
for(i in traits){
  config_list[[i]] <- c(
    paste0("outdir: /scratch/prj/neurohackpain/anqi/genodisc_validation/output/", i), 
    paste0("config_file: /scratch/prj/neurohackpain/anqi/genodisc_validation/config/config_", i, ".yaml"), 
    paste0("gwas_list: /scratch/prj/neurohackpain/anqi/DiseasesGwas/", i, "/gwas_list.txt"), 
    "resdir: /scratch/prj/neurohackpain/GenoDisc/pipeline_resources",
    "ldsc: T", 
    "magma_gene: T", 
    "magma_drugtargetor: T",
    "twas_panel_psychencode: T",
    "twas_panel_fusion: T", 
    "gtex_weights: ['Adipose_Subcutaneous','Adipose_Visceral_Omentum','Adrenal_Gland','Artery_Aorta','Artery_Coronary','Artery_Tibial','Brain_Amygdala','Brain_Anterior_cingulate_cortex_BA24','Brain_Caudate_basal_ganglia','Brain_Cerebellar_Hemisphere','Brain_Cerebellum','Brain_Cortex','Brain_Frontal_Cortex_BA9','Brain_Hippocampus','Brain_Hypothalamus','Brain_Nucleus_accumbens_basal_ganglia','Brain_Putamen_basal_ganglia','Brain_Spinal_cord_cervical_c-1','Brain_Substantia_nigra','Breast_Mammary_Tissue','Cells_EBV-transformed_lymphocytes','Colon_Sigmoid','Colon_Transverse','Esophagus_Gastroesophageal_Junction','Esophagus_Mucosa','Esophagus_Muscularis','Heart_Atrial_Appendage','Heart_Left_Ventricle','Liver','Lung','Minor_Salivary_Gland','Muscle_Skeletal','Nerve_Tibial','Ovary','Pancreas','Pituitary','Prostate','Skin_Not_Sun_Exposed_Suprapubic','Skin_Sun_Exposed_Lower_leg','Small_Intestine_Terminal_Ileum','Spleen','Stomach','Testis','Thyroid','Uterus','Vagina','Whole_Blood']", 
    "non_gtex_weights: ['METSIM.ADIPOSE.RNASEQ','CMC.BRAIN.RNASEQ','NTR.BLOOD.RNAARR','YFS.BLOOD.RNAARR']",
    "twas_gsea_cmap: T",
    "cmap_level5_prop: /users/k1806347/oliverpainfel/Data/CMAP/reprocessed/CMAP_level5/lvl5Allcompounds_population_TWAS-GSEA_prop.rds",
    "cmap_compoundinfo: /users/k1806347/oliverpainfel/Data/CMAP/compoundinfo_beta.txt",
    "cmap_cell_iname: ['HT29','A549','HA1E','A375','VCAP','PC3','MCF7']",
    "cmap_pert_itime: ['24h']",
    "cmap_pert_idose: ['10uM']",
    "twas_gsea_drugtargetor_nondirectional: T",
    "twas_gsea_drugtargetor: T",
    "tissue_magma: T"
  )
}


for(i in traits){
  write.table(config_list[[i]], 
              paste0('/scratch/prj/neurohackpain/anqi/genodisc_validation/config/config_', i, '.yaml'), 
              col.names=F, row.names=F, quote=F)
}

```

```{bash}
# Load conda env
source /scratch/prj/neurohackpain/GenoDisc/bin/activate_genodisc.sh

# Go to pipeline directory
cd /scratch/prj/neurohackpain/GenoDisc/repo/current/pipeline

for CONFIG in /scratch/prj/neurohackpain/anqi/genodisc_validation/config/*.yaml; do
    TRAIT=$(basename "$CONFIG" .yaml)
    sbatch --job-name="smk_$TRAIT" \
           --mem=2G \
           -t 1-00:00:00 \
           -p neurohack_cpu \
           --wrap="snakemake --configfile=$CONFIG --use-conda --profile slurm_interrupt --conda-prefix /scratch/prj/neurohackpain/GenoDisc/conda-envs run_package_results"
done

####
# Test using single GWAS
####

# Load conda env
source /scratch/prj/neurohackpain/GenoDisc/bin/activate_genodisc.sh

# Go to pipeline directory
cd /scratch/prj/neurohackpain/GenoDisc/repo/current/pipeline

snakemake \
  -j1 \
  -n \
  --configfile=/scratch/prj/neurohackpain/anqi/genodisc_validation/config/config_Myocardial_infarction.yaml \
  --use-conda \
  --conda-prefix /scratch/prj/neurohackpain/GenoDisc/conda-envs \
  run_package_results


```

***

#

